import type {
  DashboardPersonalItem,
  DashboardRecentItem,
  DashboardWorkItem,
} from './types'

export const dashboardUser = {
  name: 'Rayyan',
  workspace: 'Klab Workspace',
}

export const dashboardRecents: DashboardRecentItem[] = [
  {
    id: 'r1',
    title: 'Bug: Desert Camp - Form Submission',
    subtitle: 'Southern Governorate - Revamp',
    kind: 'doc',
    color: '#a952ff',
  },
  {
    id: 'r2',
    title: 'Southern Governorate - Revamp',
    subtitle: '',
    kind: 'list',
    color: '#4f8cff',
  },
  {
    id: 'r3',
    title: 'Prevent Reassignment of an Order to Another Vendor',
    subtitle: 'Faz3a Revamp',
    kind: 'doc',
    color: '#f5a524',
  },
  {
    id: 'r4',
    title: 'Faz3a Revamp',
    subtitle: '',
    kind: 'list',
    color: '#30a46c',
  },
  {
    id: 'r5',
    title: 'Admin Dashboard: Improve Casework Flow',
    subtitle: 'Southern Governorate - Revamp',
    kind: 'doc',
    color: '#ec5f8a',
  },
  {
    id: 'r6',
    title: 'Bug: Custom Form Submission Validation',
    subtitle: 'Southern Governorate - Revamp',
    kind: 'doc',
    color: '#a952ff',
  },
  {
    id: 'r7',
    title: 'QA: Performance Enhancements',
    subtitle: 'Southern Governorate - Revamp',
    kind: 'doc',
    color: '#4f8cff',
  },
]

export const dashboardMyWork: DashboardWorkItem[] = [
  {
    id: 'w1',
    title: 'Admin Dashboard: Improve People & Access resources',
    project: 'Platform',
    status: 'done',
    due: '8/7/26',
    priority: 'none',
    hasDescription: true,
    hasAttachment: true,
    tags: [{ label: 'customer', tone: 'magenta' }],
  },
  {
    id: 'w2',
    title: 'Admin Dashboard: Improve Publishing resources',
    project: 'Platform',
    status: 'done',
    due: '8/7/26',
    priority: 'normal',
    hasDescription: true,
    tags: [{ label: 'employee', tone: 'green' }],
  },
  {
    id: 'w3',
    title: 'Admin Dashboard: Improve Automations resources',
    project: 'Platform',
    status: 'done',
    due: '8/7/26',
    priority: 'none',
    hasDescription: true,
    tags: [{ label: 'vendor', tone: 'lavender' }],
  },
  {
    id: 'w4',
    title: 'Admin Dashboard: Reorganise Nova sidebar into functional sections',
    project: 'Platform',
    status: 'done',
    due: '8/7/26',
    priority: 'none',
    hasDescription: true,
  },
  {
    id: 'w5',
    title: "Bug: 'My Orders' Showing for Guests",
    project: 'Website',
    status: 'done',
    due: '8/6/26',
    priority: 'high',
    hasDescription: true,
    hasAttachment: true,
    tags: [{ label: 'bug', tone: 'lavender' }],
  },
  {
    id: 'w8',
    title: 'QA: Performance Enhancements for Casework Flow',
    project: 'Platform',
    status: 'done',
    due: '8/5/26',
    priority: 'normal',
    hasDescription: true,
  },
  {
    id: 'w9',
    title: 'Bug: Custom Form Submission Validation',
    project: 'Website',
    status: 'done',
    due: '8/5/26',
    priority: 'high',
    hasAttachment: true,
    tags: [{ label: 'bug', tone: 'lavender' }],
  },
  {
    id: 'w10',
    title: 'Admin Dashboard: Improve Casework Flow',
    project: 'Platform',
    status: 'done',
    due: '8/4/26',
    priority: 'none',
    hasDescription: true,
    tags: [{ label: 'customer', tone: 'magenta' }],
  },
  {
    id: 'w11',
    title: 'Docs: Update onboarding checklist for vendors',
    project: 'Platform',
    status: 'done',
    due: '8/4/26',
    priority: 'low',
    hasDescription: true,
  },
  {
    id: 'w12',
    title: 'Bug: Desert Camp - Form Submission',
    project: 'Website',
    status: 'done',
    due: '8/3/26',
    priority: 'urgent',
    hasDescription: true,
    hasAttachment: true,
    tags: [{ label: 'bug', tone: 'lavender' }],
  },
  {
    id: 'w13',
    title: 'Refactor notification preferences panel',
    project: 'Platform',
    status: 'done',
    due: '8/2/26',
    priority: 'normal',
  },
  {
    id: 'w14',
    title: 'Add export CSV for orders table',
    project: 'Website',
    status: 'done',
    due: '8/1/26',
    priority: 'high',
    hasDescription: true,
    tags: [{ label: 'web', tone: 'blue' }],
  },
  {
    id: 'w6',
    title: 'Wire empty states for Inbox tabs',
    project: 'Platform',
    status: 'in_progress',
    due: 'Today',
    priority: 'high',
    hasDescription: true,
    tags: [{ label: 'admin dashboard', tone: 'lavender' }],
  },
  {
    id: 'w7',
    title: 'Fix date picker overflow on mobile',
    project: 'Website Redesign',
    status: 'todo',
    due: 'Today',
    priority: 'urgent',
    tags: [
      { label: 'ui / ux', tone: 'grey' },
      { label: 'web', tone: 'blue' },
    ],
  },
  {
    id: 'w15',
    title: 'Design review: Assigned to me empty state',
    project: 'Platform',
    status: 'todo',
    due: 'Tomorrow',
    priority: 'normal',
    hasDescription: true,
    tags: [{ label: 'ui / ux', tone: 'grey' }],
  },
  {
    id: 'w16',
    title: 'API: Paginate inbox notifications feed',
    project: 'Platform',
    status: 'in_progress',
    due: '9/2/26',
    priority: 'high',
    hasAttachment: true,
  },
  {
    id: 'w17',
    title: 'Fix sticky header overlap on mobile Safari',
    project: 'Website Redesign',
    status: 'todo',
    due: '9/3/26',
    priority: 'urgent',
    hasDescription: true,
    tags: [{ label: 'bug', tone: 'lavender' }],
  },
  {
    id: 'w18',
    title: 'Add keyboard shortcuts for task list',
    project: 'Platform',
    status: 'todo',
    due: '9/5/26',
    priority: 'low',
  },
  {
    id: 'w19',
    title: 'Sync personal list with backend draft API',
    project: 'Platform',
    status: 'in_progress',
    due: '9/6/26',
    priority: 'normal',
    hasDescription: true,
    tags: [{ label: 'employee', tone: 'green' }],
  },
  {
    id: 'w20',
    title: 'Build card footer actions for Assigned to me',
    project: 'Platform',
    status: 'todo',
    due: '9/7/26',
    priority: 'normal',
    hasDescription: true,
    tags: [{ label: 'admin dashboard', tone: 'lavender' }],
  },
  {
    id: 'w21',
    title: 'Bug: Search clears filter on blur',
    project: 'Platform',
    status: 'todo',
    due: '9/8/26',
    priority: 'high',
    hasAttachment: true,
    tags: [{ label: 'bug', tone: 'lavender' }],
  },
  {
    id: 'w22',
    title: 'Add skeleton loaders for Recents list',
    project: 'Website Redesign',
    status: 'in_progress',
    due: '9/8/26',
    priority: 'low',
    tags: [{ label: 'ui / ux', tone: 'grey' }],
  },
  {
    id: 'w23',
    title: 'Implement drag reorder for Personal List',
    project: 'Platform',
    status: 'todo',
    due: '9/9/26',
    priority: 'urgent',
    hasDescription: true,
  },
  {
    id: 'w24',
    title: 'QA: Verify sticky group headers on Firefox',
    project: 'Platform',
    status: 'todo',
    due: '9/10/26',
    priority: 'normal',
    tags: [{ label: 'web', tone: 'blue' }],
  },
  {
    id: 'w25',
    title: 'API: Soft-delete completed tasks archive endpoint',
    project: 'Platform',
    status: 'in_progress',
    due: '9/11/26',
    priority: 'high',
    hasDescription: true,
    hasAttachment: true,
  },
  {
    id: 'w26',
    title: 'Update toast colors to use theme tokens',
    project: 'Website Redesign',
    status: 'todo',
    due: '9/12/26',
    priority: 'low',
    tags: [{ label: 'ui / ux', tone: 'grey' }],
  },
  {
    id: 'w27',
    title: 'Bug: Due date sort breaks on Tomorrow label',
    project: 'Platform',
    status: 'todo',
    due: 'Today',
    priority: 'urgent',
    hasDescription: true,
    tags: [{ label: 'bug', tone: 'lavender' }],
  },
  {
    id: 'w28',
    title: 'Polish Inbox clear-all confirmation modal',
    project: 'Platform',
    status: 'in_progress',
    due: 'Tomorrow',
    priority: 'normal',
    tags: [{ label: 'customer', tone: 'magenta' }],
  },
]

export const dashboardPersonalList: DashboardPersonalItem[] = [
  { id: 'p1', title: 'Finalize campaign brief', done: false },
  { id: 'p2', title: 'Review sprint notes', done: false },
  { id: 'p3', title: 'Send weekly update', done: true },
]
