import type { Component } from 'vue'
import {
  Anchor,
  Archive,
  Award,
  Banknote,
  BatteryFull,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  ChartColumn,
  CircleDot,
  ClipboardList,
  Code2,
  Compass,
  FolderKanban,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Layers,
  LayoutDashboard,
  Lightbulb,
  MapPin,
  Megaphone,
  MessageSquare,
  Music,
  Package,
  Palette,
  Rocket,
  Settings,
  Shield,
  Sparkles,
  Star,
  Target,
  Trophy,
  Users,
  Wallet,
  Wrench,
  Zap,
} from '@lucide/vue'

export type SpaceIconOption = {
  name: string
  icon: Component
}

/** Curated Lucide set for space / project icons */
export const spaceIconOptions: SpaceIconOption[] = [
  { name: 'Users', icon: Users },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'Building2', icon: Building2 },
  { name: 'FolderKanban', icon: FolderKanban },
  { name: 'Layers', icon: Layers },
  { name: 'LayoutDashboard', icon: LayoutDashboard },
  { name: 'Rocket', icon: Rocket },
  { name: 'Target', icon: Target },
  { name: 'Zap', icon: Zap },
  { name: 'Star', icon: Star },
  { name: 'Heart', icon: Heart },
  { name: 'Home', icon: Home },
  { name: 'Globe', icon: Globe },
  { name: 'Compass', icon: Compass },
  { name: 'MapPin', icon: MapPin },
  { name: 'Calendar', icon: Calendar },
  { name: 'Bell', icon: Bell },
  { name: 'MessageSquare', icon: MessageSquare },
  { name: 'Megaphone', icon: Megaphone },
  { name: 'Lightbulb', icon: Lightbulb },
  { name: 'Sparkles', icon: Sparkles },
  { name: 'Award', icon: Award },
  { name: 'Trophy', icon: Trophy },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'BookOpen', icon: BookOpen },
  { name: 'ClipboardList', icon: ClipboardList },
  { name: 'ChartColumn', icon: ChartColumn },
  { name: 'Code2', icon: Code2 },
  { name: 'Settings', icon: Settings },
  { name: 'Wrench', icon: Wrench },
  { name: 'Shield', icon: Shield },
  { name: 'Package', icon: Package },
  { name: 'Box', icon: Box },
  { name: 'Archive', icon: Archive },
  { name: 'Gift', icon: Gift },
  { name: 'Palette', icon: Palette },
  { name: 'Camera', icon: Camera },
  { name: 'Music', icon: Music },
  { name: 'Wallet', icon: Wallet },
  { name: 'Banknote', icon: Banknote },
  { name: 'Anchor', icon: Anchor },
  { name: 'BatteryFull', icon: BatteryFull },
  { name: 'CircleDot', icon: CircleDot },
]

export function findSpaceIcon(name: string | null | undefined) {
  if (!name) return null
  return spaceIconOptions.find((item) => item.name === name) ?? null
}
