import type { InboxGroup, InboxTabId } from './types'

const primaryGroups: InboxGroup[] = [
  {
    id: 'earlier-this-month',
    label: 'Earlier this month',
    items: [
      {
        id: 'p1',
        title: 'Bug: Dates',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'assigned this task to you',
        unread: true,
        count: 7,
        date: 'Sep 7',
      },
      {
        id: 'p2',
        title: 'UI Adjustments: Application...',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'ok no worries @rayyan.klabs — I will update the spacing and ship it today.',
        unread: true,
        count: 17,
        date: 'Sep 7',
      },
      {
        id: 'p3',
        title: 'New Task',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'assigned this task to you',
        unread: true,
        count: 5,
        date: 'Sep 7',
      },
      {
        id: 'p4',
        title: 'List View',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'assigned this task to you',
        unread: false,
        count: 3,
        date: 'Sep 7',
      },
      {
        id: 'p5',
        title: 'UI Adjustments: Application...',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'assigned this task to you',
        unread: true,
        count: 8,
        date: 'Sep 7',
      },
      {
        id: 'p6',
        title: 'New Task',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'assigned this task to you',
        unread: false,
        count: 4,
        date: 'Sep 7',
      },
      {
        id: 'p7',
        title: 'List View',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'assigned this task to you',
        unread: true,
        count: 2,
        date: 'Sep 7',
      },
    ],
  },
  {
    id: 'august',
    label: 'August',
    items: [
      {
        id: 'p8',
        title: 'UI Adjustments: Application...',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'AB', color: '#6b7280' },
        action: 'assigned this task to you',
        unread: true,
        count: 11,
        date: 'Aug 30',
      },
      {
        id: 'p9',
        title: 'New Task',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'assigned this task to you',
        unread: false,
        count: 6,
        date: 'Aug 30',
      },
      {
        id: 'p10',
        title: 'List View',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'assigned this task to you',
        unread: true,
        count: 9,
        date: 'Aug 30',
      },
      {
        id: 'p11',
        title: 'UI Adjustments: Application...',
        status: 'success',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'assigned this task to you',
        unread: false,
        count: 14,
        date: 'Aug 30',
      },
      {
        id: 'p12',
        title: 'Project Overview',
        status: 'doc',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'mentioned you',
        unread: true,
        count: 1,
        date: 'Aug 28',
      },
      {
        id: 'p13',
        title: 'Sprint blockers',
        status: 'warning',
        actor: { name: 'Ayesha', initials: 'AK', color: '#f59e0b' },
        action: 'requested a review',
        unread: false,
        count: 3,
        date: 'Aug 22',
      },
    ],
  },
]

const otherGroups: InboxGroup[] = [
  {
    id: 'earlier-this-month',
    label: 'Earlier this month',
    items: [
      {
        id: 'o1',
        title: 'Design QA checklist',
        status: 'warning',
        actor: { name: 'Ayesha', initials: 'AK', color: '#f59e0b' },
        action: 'left a comment for you',
        unread: true,
        count: 4,
        date: 'Sep 6',
      },
      {
        id: 'o2',
        title: 'API contract updates',
        status: 'success',
        actor: { name: 'Hassan', initials: 'HK', color: '#10b981' },
        action: 'mentioned you in @rayyan.klabs thread',
        unread: true,
        count: 12,
        date: 'Sep 5',
      },
      {
        id: 'o3',
        title: 'Onboarding copy pass',
        status: 'doc',
        actor: { name: 'Mira', initials: 'MR', color: '#8b5cf6' },
        action: 'shared a doc with you',
        unread: false,
        count: 2,
        date: 'Sep 4',
      },
      {
        id: 'o4',
        title: 'Billing edge cases',
        status: 'danger',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'assigned this task to you',
        unread: true,
        count: 6,
        date: 'Sep 3',
      },
    ],
  },
  {
    id: 'august',
    label: 'August',
    items: [
      {
        id: 'o5',
        title: 'Notification preferences',
        status: 'success',
        actor: { name: 'Ali', initials: 'AL', color: '#64748b' },
        action: 'requested feedback',
        unread: false,
        count: 3,
        date: 'Aug 29',
      },
      {
        id: 'o6',
        title: 'Workspace invites',
        status: 'neutral',
        actor: { name: 'Sara', initials: 'SR', color: '#ec4899' },
        action: 'added you to a space',
        unread: true,
        date: 'Aug 21',
      },
    ],
  },
]

const laterGroups: InboxGroup[] = [
  {
    id: 'earlier-this-month',
    label: 'Earlier this month',
    items: [
      {
        id: 'l1',
        title: 'Follow up: Dates regression',
        status: 'warning',
        actor: { name: 'shakeeb', initials: 'SK', color: '#5b8def' },
        action: 'reminded you about this task',
        unread: true,
        count: 2,
        date: 'Sep 8',
      },
      {
        id: 'l2',
        title: 'Release notes draft',
        status: 'doc',
        actor: { name: 'Mira', initials: 'MR', color: '#8b5cf6' },
        action: 'snoozed until next week',
        unread: false,
        count: 1,
        date: 'Sep 2',
      },
      {
        id: 'l3',
        title: 'Customer feedback triage',
        status: 'success',
        actor: { name: 'Ayesha', initials: 'AK', color: '#f59e0b' },
        action: 'asked you to revisit later',
        unread: true,
        count: 5,
        date: 'Sep 1',
      },
    ],
  },
  {
    id: 'august',
    label: 'August',
    items: [
      {
        id: 'l4',
        title: 'Roadmap sync notes',
        status: 'neutral',
        actor: { name: 'Hassan', initials: 'HK', color: '#10b981' },
        action: 'saved this for later',
        unread: false,
        count: 4,
        date: 'Aug 26',
      },
      {
        id: 'l5',
        title: 'Perf budget review',
        status: 'danger',
        actor: { name: 'Ali', initials: 'AL', color: '#64748b' },
        action: 'assigned this task to you',
        unread: true,
        count: 7,
        date: 'Aug 18',
      },
    ],
  },
]

export const inboxFeedByTab: Record<Exclude<InboxTabId, 'cleared'>, InboxGroup[]> = {
  primary: primaryGroups,
  other: otherGroups,
  later: laterGroups,
}
